"""initial schema without date index

Revision ID: 3108f46d1c57
Revises: 
Create Date: 2025-06-12 05:38:23.616058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3108f46d1c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phish_campaigns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phish_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sent_by', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('link_hash', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phish_events', schema=None) as batch_op:
        batch_op.create_index('idx_email_campaign', ['email', 'campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phish_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phish_events_clicked_at'), ['clicked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_phish_events_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_phish_events_link_hash'), ['link_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_phish_events_sent_by'), ['sent_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phish_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phish_events_sent_by'))
        batch_op.drop_index(batch_op.f('ix_phish_events_link_hash'))
        batch_op.drop_index(batch_op.f('ix_phish_events_email'))
        batch_op.drop_index(batch_op.f('ix_phish_events_clicked_at'))
        batch_op.drop_index(batch_op.f('ix_phish_events_campaign_id'))
        batch_op.drop_index('idx_email_campaign')

    op.drop_table('phish_events')
    op.drop_table('phish_campaigns')
    # ### end Alembic commands ###
